# Generated by Django 3.2.5 on 2021-07-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dishingredient',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
    ]
