# Generated by Django 3.2.5 on 2021-07-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20210728_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
    ]
