# Generated by Django 3.2.5 on 2021-08-08 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20210802_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['created'], 'verbose_name_plural': 'Dishes'},
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.ingredient')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_dish', to='dishes.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(through='dishes.OrderDish', to='dishes.Dish'),
        ),
    ]
