# Generated by Django 3.2.5 on 2021-08-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_auto_20210808_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingredient',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ingredients', to='dishes.order'),
        ),
    ]
