# Generated by Django 3.2.5 on 2021-08-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_orderingredient_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Dishes'},
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='dishes.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ingredients', to='dishes.ingredient'),
        ),
    ]
